### ISSUE TITLE
article par skywodd

### ISSUE THREAD

**Issue by tarekziade** [faitmain/faitmain.org#96]
cc @skywodd

**Comment by skywodd** [comment]
Au programme du volume 3 : de la transformée de Fourier rapide.
256x16 leds, soit 4096 pixels bicolores de pure concentré de Fourrier en audio-injectable :)
- [x] Partie microcontrôleur (Fidèle ATmega644 à 16MHz)
- [x] Partie analogique (Montage ampli-op niveau lycée++)
- [x] Code d'essai (AVR-C & Makefile)
- [x] Prototype réduit (64x16, fonctionnel)
  ![img_20130531_233858](https://f.cloud.github.com/assets/1381853/604110/507842ee-cceb-11e2-874a-6652d6e7e6ae.jpg)
- [x] Code final
- [x] Montage final
- [x] Rédaction de l'article & photo
- [x] Vidéo de démo

**Comment by skywodd** [comment]
Sujets annexes facilement réalisables une fois le montage final réalisé :
- Game of life (code prés & testé, démo pourri ici : http://www.youtube.com/watch?v=1qI1527fi5I)
- Afficheur graphique 3 couleurs (rouge, vert, orange) +/- générique

**Comment by skywodd** [comment]
# Update du 13/07

## Fini
- Code final
- Montage final
- Vidéo de démo

## TODO
- [x] Photo pour l'article
- [x] Schémas sous Eagle
- [x] Rédaction

## Code source dispo
- Code de base + fonctions de dessin par pixel
- Game of life (surface de 96x64 pixels, refresh à 2Hz environ)
- FFT, choix de l'affichage logarithmique ou linéaire par bouton
  (FFT sur 128 points mais affichage uniquement des bandes 2 à 98, sur 64 pixels de haut)

**Comment by tarekziade** [comment]
Brouillon: http://next.faitmain.org/volume-3/ledmatrix.html
